// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: eastmony.proto

package eastMoney

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HelloRequest 请求结构
type GetAllFundCodeInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllFundCodeInfoRequest) Reset() {
	*x = GetAllFundCodeInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eastmony_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFundCodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFundCodeInfoRequest) ProtoMessage() {}

func (x *GetAllFundCodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eastmony_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFundCodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAllFundCodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_eastmony_proto_rawDescGZIP(), []int{0}
}

type FundCodeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FundCodeList) Reset() {
	*x = FundCodeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eastmony_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FundCodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundCodeList) ProtoMessage() {}

func (x *FundCodeList) ProtoReflect() protoreflect.Message {
	mi := &file_eastmony_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundCodeList.ProtoReflect.Descriptor instead.
func (*FundCodeList) Descriptor() ([]byte, []int) {
	return file_eastmony_proto_rawDescGZIP(), []int{1}
}

// HelloResponse 响应结构
type GetAllFundCodeInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FundCodeList []*FundCodeList `protobuf:"bytes,1,rep,name=fundCodeList,proto3" json:"fundCodeList,omitempty"`
}

func (x *GetAllFundCodeInfoResponse) Reset() {
	*x = GetAllFundCodeInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eastmony_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFundCodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFundCodeInfoResponse) ProtoMessage() {}

func (x *GetAllFundCodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eastmony_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFundCodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAllFundCodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_eastmony_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllFundCodeInfoResponse) GetFundCodeList() []*FundCodeList {
	if x != nil {
		return x.FundCodeList
	}
	return nil
}

var File_eastmony_proto protoreflect.FileDescriptor

var file_eastmony_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x61, 0x73, 0x74, 0x6d, 0x6f, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x45, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x22, 0x1b, 0x0a, 0x19, 0x67,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x66, 0x75, 0x6e, 0x64,
	0x43, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x1a, 0x67, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x46, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x66, 0x75, 0x6e, 0x64, 0x43, 0x6f,
	0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x45,
	0x61, 0x73, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x66, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x64,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0c, 0x66, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x32, 0x70, 0x0a, 0x09, 0x45, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79,
	0x12, 0x63, 0x0a, 0x12, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x75, 0x6e, 0x64, 0x43, 0x6f,
	0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x2e, 0x45, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x2e, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x64,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x45,
	0x61, 0x73, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46,
	0x75, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x3b, 0x65, 0x61, 0x73, 0x74,
	0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_eastmony_proto_rawDescOnce sync.Once
	file_eastmony_proto_rawDescData = file_eastmony_proto_rawDesc
)

func file_eastmony_proto_rawDescGZIP() []byte {
	file_eastmony_proto_rawDescOnce.Do(func() {
		file_eastmony_proto_rawDescData = protoimpl.X.CompressGZIP(file_eastmony_proto_rawDescData)
	})
	return file_eastmony_proto_rawDescData
}

var file_eastmony_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_eastmony_proto_goTypes = []interface{}{
	(*GetAllFundCodeInfoRequest)(nil),  // 0: EastMoney.getAllFundCodeInfoRequest
	(*FundCodeList)(nil),               // 1: EastMoney.fundCodeList
	(*GetAllFundCodeInfoResponse)(nil), // 2: EastMoney.getAllFundCodeInfoResponse
}
var file_eastmony_proto_depIdxs = []int32{
	1, // 0: EastMoney.getAllFundCodeInfoResponse.fundCodeList:type_name -> EastMoney.fundCodeList
	0, // 1: EastMoney.EastMoney.getAllFundCodeInfo:input_type -> EastMoney.getAllFundCodeInfoRequest
	2, // 2: EastMoney.EastMoney.getAllFundCodeInfo:output_type -> EastMoney.getAllFundCodeInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_eastmony_proto_init() }
func file_eastmony_proto_init() {
	if File_eastmony_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_eastmony_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFundCodeInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eastmony_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FundCodeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eastmony_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFundCodeInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eastmony_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eastmony_proto_goTypes,
		DependencyIndexes: file_eastmony_proto_depIdxs,
		MessageInfos:      file_eastmony_proto_msgTypes,
	}.Build()
	File_eastmony_proto = out.File
	file_eastmony_proto_rawDesc = nil
	file_eastmony_proto_goTypes = nil
	file_eastmony_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EastMoneyClient is the client API for EastMoney service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EastMoneyClient interface {
	// 从天天基金获取所有基金信息
	GetAllFundCodeInfo(ctx context.Context, in *GetAllFundCodeInfoRequest, opts ...grpc.CallOption) (*GetAllFundCodeInfoResponse, error)
}

type eastMoneyClient struct {
	cc grpc.ClientConnInterface
}

func NewEastMoneyClient(cc grpc.ClientConnInterface) EastMoneyClient {
	return &eastMoneyClient{cc}
}

func (c *eastMoneyClient) GetAllFundCodeInfo(ctx context.Context, in *GetAllFundCodeInfoRequest, opts ...grpc.CallOption) (*GetAllFundCodeInfoResponse, error) {
	out := new(GetAllFundCodeInfoResponse)
	err := c.cc.Invoke(ctx, "/EastMoney.EastMoney/getAllFundCodeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EastMoneyServer is the server API for EastMoney service.
type EastMoneyServer interface {
	// 从天天基金获取所有基金信息
	GetAllFundCodeInfo(context.Context, *GetAllFundCodeInfoRequest) (*GetAllFundCodeInfoResponse, error)
}

// UnimplementedEastMoneyServer can be embedded to have forward compatible implementations.
type UnimplementedEastMoneyServer struct {
}

func (*UnimplementedEastMoneyServer) GetAllFundCodeInfo(context.Context, *GetAllFundCodeInfoRequest) (*GetAllFundCodeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllFundCodeInfo not implemented")
}

func RegisterEastMoneyServer(s *grpc.Server, srv EastMoneyServer) {
	s.RegisterService(&_EastMoney_serviceDesc, srv)
}

func _EastMoney_GetAllFundCodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFundCodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EastMoneyServer).GetAllFundCodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EastMoney.EastMoney/GetAllFundCodeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EastMoneyServer).GetAllFundCodeInfo(ctx, req.(*GetAllFundCodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EastMoney_serviceDesc = grpc.ServiceDesc{
	ServiceName: "EastMoney.EastMoney",
	HandlerType: (*EastMoneyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getAllFundCodeInfo",
			Handler:    _EastMoney_GetAllFundCodeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eastmony.proto",
}
